#include <SPECS.h>
#include <SPECS_SYS.h>
#include <SPECS_EXE.h>

void
_CHECK_SYSCONF(void *_alg, void *__alg)
/* _alg points to ExeSpecDefRow */
/* __alg points to AlgorithmSpecDefIndexEntry */
{
	/* P-code pointer definition */
	void *_out, *__out;

	/* Local input/output variable definition */
	INTEGER	ERRNO;
	STRING	ERRMSG;
	STRING	SMODE;
	STRING	OP_LANG;
	STRING	ADTFORMAT;
	STRING	CLEARONRETEST;
	STRING	CLEARONREJECT;
	STRING	PORTID;
	STRING	PROJID;
	STRING	HOSTNAME;
	STRING	ADTLOGGING;

	/* P-code pointer initialization */
	_out = TPLEXECOUT(_alg);
	__out = TPLLASTOUT(__alg);

	/* Local variable initialization */
	TPLINITMEM(&ERRNO, _TYPEI, 0, 0);
	TPLINITMEM(&ERRMSG, _TYPES, 0, 0);
	TPLINITMEM(&SMODE, _TYPES, 0, 0);
	TPLINITMEM(&OP_LANG, _TYPES, 0, 0);
	TPLINITMEM(&ADTFORMAT, _TYPES, 0, 0);
	TPLINITMEM(&CLEARONRETEST, _TYPES, 0, 0);
	TPLINITMEM(&CLEARONREJECT, _TYPES, 0, 0);
	TPLINITMEM(&PORTID, _TYPES, 0, 0);
	TPLINITMEM(&PROJID, _TYPES, 0, 0);
	TPLINITMEM(&HOSTNAME, _TYPES, 0, 0);
	TPLINITMEM(&ADTLOGGING, _TYPES, 0, 0);

	/* Algorithm input variable setting */

	/* Algorithm output variable setting */
	TPLGETEXECOUTVAR(_out, 0, &ERRNO);
	TPLGETEXECOUTVAR(_out, 1, &ERRMSG);
	TPLGETEXECOUTVAR(_out, 2, &SMODE);
	TPLGETEXECOUTVAR(_out, 3, &OP_LANG);
	TPLGETEXECOUTVAR(_out, 4, &ADTFORMAT);
	TPLGETEXECOUTVAR(_out, 5, &CLEARONRETEST);
	TPLGETEXECOUTVAR(_out, 6, &CLEARONREJECT);
	TPLGETEXECOUTVAR(_out, 7, &PORTID);
	TPLGETEXECOUTVAR(_out, 8, &PROJID);
	TPLGETEXECOUTVAR(_out, 9, &HOSTNAME);
	TPLGETEXECOUTVAR(_out, 10, &ADTLOGGING);
	TPLPUTLASTOUTVAR(__out, 0, &ERRNO);
	TPLPUTLASTOUTVAR(__out, 1, &ERRMSG);
	TPLPUTLASTOUTVAR(__out, 2, &SMODE);
	TPLPUTLASTOUTVAR(__out, 3, &OP_LANG);
	TPLPUTLASTOUTVAR(__out, 4, &ADTFORMAT);
	TPLPUTLASTOUTVAR(__out, 5, &CLEARONRETEST);
	TPLPUTLASTOUTVAR(__out, 6, &CLEARONREJECT);
	TPLPUTLASTOUTVAR(__out, 7, &PORTID);
	TPLPUTLASTOUTVAR(__out, 8, &PROJID);
	TPLPUTLASTOUTVAR(__out, 9, &HOSTNAME);
	TPLPUTLASTOUTVAR(__out, 10, &ADTLOGGING);

	/* Algorithm invocation */
	CHECK_SYSCONF(&ERRNO,&ERRMSG,&SMODE,&OP_LANG,&ADTFORMAT,&CLEARONRETEST,&CLEARONREJECT,&PORTID,&PROJID,&HOSTNAME,&ADTLOGGING);

	/* Algorithm output variable setting */
	TPLPUTEXECOUTVAR(_out, 0, &ERRNO);
	TPLPUTEXECOUTVAR(_out, 1, &ERRMSG);
	TPLPUTEXECOUTVAR(_out, 2, &SMODE);
	TPLPUTEXECOUTVAR(_out, 3, &OP_LANG);
	TPLPUTEXECOUTVAR(_out, 4, &ADTFORMAT);
	TPLPUTEXECOUTVAR(_out, 5, &CLEARONRETEST);
	TPLPUTEXECOUTVAR(_out, 6, &CLEARONREJECT);
	TPLPUTEXECOUTVAR(_out, 7, &PORTID);
	TPLPUTEXECOUTVAR(_out, 8, &PROJID);
	TPLPUTEXECOUTVAR(_out, 9, &HOSTNAME);
	TPLPUTEXECOUTVAR(_out, 10, &ADTLOGGING);
	TPLPUTLASTOUTVAR(__out, 0, &ERRNO);
	TPLPUTLASTOUTVAR(__out, 1, &ERRMSG);
	TPLPUTLASTOUTVAR(__out, 2, &SMODE);
	TPLPUTLASTOUTVAR(__out, 3, &OP_LANG);
	TPLPUTLASTOUTVAR(__out, 4, &ADTFORMAT);
	TPLPUTLASTOUTVAR(__out, 5, &CLEARONRETEST);
	TPLPUTLASTOUTVAR(__out, 6, &CLEARONREJECT);
	TPLPUTLASTOUTVAR(__out, 7, &PORTID);
	TPLPUTLASTOUTVAR(__out, 8, &PROJID);
	TPLPUTLASTOUTVAR(__out, 9, &HOSTNAME);
	TPLPUTLASTOUTVAR(__out, 10, &ADTLOGGING);
}

void
__CHECK_SYSCONF(void *__alg)
/* __alg points to AlgorithmSpecDefIndexEntry */
{
	/* P-code pointer definition */
	void *__out;

	/* Local input/output variable definition */
	INTEGER	ERRNO;
	STRING	ERRMSG;
	STRING	SMODE;
	STRING	OP_LANG;
	STRING	ADTFORMAT;
	STRING	CLEARONRETEST;
	STRING	CLEARONREJECT;
	STRING	PORTID;
	STRING	PROJID;
	STRING	HOSTNAME;
	STRING	ADTLOGGING;

	/* P-code pointer initialization */
	__out = TPLLASTOUT(__alg);

	/* Local variable initialization */
	TPLINITMEM(&ERRNO, _TYPEI, 0, 0);
	TPLINITMEM(&ERRMSG, _TYPES, 0, 0);
	TPLINITMEM(&SMODE, _TYPES, 0, 0);
	TPLINITMEM(&OP_LANG, _TYPES, 0, 0);
	TPLINITMEM(&ADTFORMAT, _TYPES, 0, 0);
	TPLINITMEM(&CLEARONRETEST, _TYPES, 0, 0);
	TPLINITMEM(&CLEARONREJECT, _TYPES, 0, 0);
	TPLINITMEM(&PORTID, _TYPES, 0, 0);
	TPLINITMEM(&PROJID, _TYPES, 0, 0);
	TPLINITMEM(&HOSTNAME, _TYPES, 0, 0);
	TPLINITMEM(&ADTLOGGING, _TYPES, 0, 0);

	/* Algorithm input variable setting */

	/* Algorithm output variable setting */
	TPLGETLASTOUTVAR(__out, 0, &ERRNO);
	TPLGETLASTOUTVAR(__out, 1, &ERRMSG);
	TPLGETLASTOUTVAR(__out, 2, &SMODE);
	TPLGETLASTOUTVAR(__out, 3, &OP_LANG);
	TPLGETLASTOUTVAR(__out, 4, &ADTFORMAT);
	TPLGETLASTOUTVAR(__out, 5, &CLEARONRETEST);
	TPLGETLASTOUTVAR(__out, 6, &CLEARONREJECT);
	TPLGETLASTOUTVAR(__out, 7, &PORTID);
	TPLGETLASTOUTVAR(__out, 8, &PROJID);
	TPLGETLASTOUTVAR(__out, 9, &HOSTNAME);
	TPLGETLASTOUTVAR(__out, 10, &ADTLOGGING);

	/* Algorithm invocation */
	CHECK_SYSCONF(&ERRNO,&ERRMSG,&SMODE,&OP_LANG,&ADTFORMAT,&CLEARONRETEST,&CLEARONREJECT,&PORTID,&PROJID,&HOSTNAME,&ADTLOGGING);

	/* Algorithm output variable setting */
	TPLPUTLASTOUTVAR(__out, 0, &ERRNO);
	TPLPUTLASTOUTVAR(__out, 1, &ERRMSG);
	TPLPUTLASTOUTVAR(__out, 2, &SMODE);
	TPLPUTLASTOUTVAR(__out, 3, &OP_LANG);
	TPLPUTLASTOUTVAR(__out, 4, &ADTFORMAT);
	TPLPUTLASTOUTVAR(__out, 5, &CLEARONRETEST);
	TPLPUTLASTOUTVAR(__out, 6, &CLEARONREJECT);
	TPLPUTLASTOUTVAR(__out, 7, &PORTID);
	TPLPUTLASTOUTVAR(__out, 8, &PROJID);
	TPLPUTLASTOUTVAR(__out, 9, &HOSTNAME);
	TPLPUTLASTOUTVAR(__out, 10, &ADTLOGGING);
}
