#include <SPECS.h>
#include <SPECS_SYS.h>
#include <SPECS_DBG.h>

void
_CHECK_SYSCONF(void *_alg)
{
}

void
__CHECK_SYSCONF(void *_alg)
/* _alg points to AlgorithmDefinition */
{
	/* Data pointer definition */
	void *_out;

	/* Local input/output variable definition */
	INTEGER	ERRNO;
	STRING	ERRMSG;
	STRING	SMODE;
	STRING	OP_LANG;
	STRING	ADTFORMAT;
	STRING	CLEARONRETEST;
	STRING	CLEARONREJECT;
	STRING	PORTID;
	STRING	PROJID;
	STRING	HOSTNAME;
	STRING	ADTLOGGING;

	/* Data pointer initialization */
	_out = TPLDEBUGOUT(_alg);

	/* Local variable initialization */
	TPLINITMEM(&ERRNO, _TYPEI, 0, 0);
	TPLINITMEM(&ERRMSG, _TYPES, 0, 0);
	TPLINITMEM(&SMODE, _TYPES, 0, 0);
	TPLINITMEM(&OP_LANG, _TYPES, 0, 0);
	TPLINITMEM(&ADTFORMAT, _TYPES, 0, 0);
	TPLINITMEM(&CLEARONRETEST, _TYPES, 0, 0);
	TPLINITMEM(&CLEARONREJECT, _TYPES, 0, 0);
	TPLINITMEM(&PORTID, _TYPES, 0, 0);
	TPLINITMEM(&PROJID, _TYPES, 0, 0);
	TPLINITMEM(&HOSTNAME, _TYPES, 0, 0);
	TPLINITMEM(&ADTLOGGING, _TYPES, 0, 0);

	/* Algorithm input variable setting */

	/* Algorithm output variable setting */
	TPLGETDEBUGOUTVAR(_out, 0, &ERRNO);
	TPLGETDEBUGOUTVAR(_out, 1, &ERRMSG);
	TPLGETDEBUGOUTVAR(_out, 2, &SMODE);
	TPLGETDEBUGOUTVAR(_out, 3, &OP_LANG);
	TPLGETDEBUGOUTVAR(_out, 4, &ADTFORMAT);
	TPLGETDEBUGOUTVAR(_out, 5, &CLEARONRETEST);
	TPLGETDEBUGOUTVAR(_out, 6, &CLEARONREJECT);
	TPLGETDEBUGOUTVAR(_out, 7, &PORTID);
	TPLGETDEBUGOUTVAR(_out, 8, &PROJID);
	TPLGETDEBUGOUTVAR(_out, 9, &HOSTNAME);
	TPLGETDEBUGOUTVAR(_out, 10, &ADTLOGGING);

	/* Algorithm invocation */
	CHECK_SYSCONF(&ERRNO,&ERRMSG,&SMODE,&OP_LANG,&ADTFORMAT,&CLEARONRETEST,&CLEARONREJECT,&PORTID,&PROJID,&HOSTNAME,&ADTLOGGING);

	/* Algorithm output variable setting */
	TPLPUTDEBUGOUTVAR(_out, 0, &ERRNO);
	TPLPUTDEBUGOUTVAR(_out, 1, &ERRMSG);
	TPLPUTDEBUGOUTVAR(_out, 2, &SMODE);
	TPLPUTDEBUGOUTVAR(_out, 3, &OP_LANG);
	TPLPUTDEBUGOUTVAR(_out, 4, &ADTFORMAT);
	TPLPUTDEBUGOUTVAR(_out, 5, &CLEARONRETEST);
	TPLPUTDEBUGOUTVAR(_out, 6, &CLEARONREJECT);
	TPLPUTDEBUGOUTVAR(_out, 7, &PORTID);
	TPLPUTDEBUGOUTVAR(_out, 8, &PROJID);
	TPLPUTDEBUGOUTVAR(_out, 9, &HOSTNAME);
	TPLPUTDEBUGOUTVAR(_out, 10, &ADTLOGGING);
}
