#!/bin/sh
#
# Restart using Tcl/Tk with the hub UI script.
# Additional command line arguments can be Tcl statements
#
# (C) Copyright Keysight Technologies, Inc. 2003-2015
# All Rights are reserved.
#
# Copying Or Other Reproduction Of This Program Except For Archival Purposes
# Is Prohibited Without The Prior Written Consent Of Keysight Technologies.
#
#
# Use -notk to run detached from X-windows.
# \
exec dmh_wish -f "$0" "$@"

set use_compiled 1
foreach cmd_option $argv {
    if {[string range $cmd_option 0 0] == "-"} {
        #remove the - character (ex. -show becomes show)
        regsub -all {\-} $cmd_option {} cmd_option
        if { $cmd_option == "source" } { set use_compiled 0 }
    }
}

package require dmh
dmh_import

if {$use_compiled == 1} {
    cd bin
    if { [file exist libtbcload1.3.sl] } {
        load libtbcload1.3.sl
    }
    if { [file exist libtbcload1.4.so] } {
        load libtbcload1.4.so
    }
    set allfiles [glob *.tbc]

    foreach file $allfiles {
        source $file
    }
    cd ..
} else {
    cd src
    set allfiles [glob *.tcl]

    foreach file $allfiles {
        source $file
    }
    cd ..
}

#start application with compiled code (1)
main
