/* XPM */
static char * plan5_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"38 38 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	c #7F7F7F7F7F7F",
"o	s iconColor1	m black	c black",
"O	c #E6E6E6E6E6E6",
"+	c #B3B3B3B3B3B3",
"@	c #00006565CBCB",
"#	s iconColor7	m white	c cyan",
"$	s iconColor4	m white	c green",
"%	c #CBCBCBCBCBCB",
/* pixels */
" ..........                           ",
" XXXXXXXXXXo                   .....  ",
" OOOOOOOOOOo                   .ooo.o ",
" OOOOOOOOOOo   ............    .ooo.o ",
" ++++++++++o  ..............   .ooo.o ",
" ..........o  XXXXXXXXXXXXXXo  .....o ",
" ..........o  XXXXXXXXXXXXXXo  ooooo. ",
" ..........o  XXXXXXXXXXXXXXo  OOOOO. ",
" ..........o  ..............o  OOOOOo ",
" OOOOOOOOOOo   ............o   OOOOOo ",
" OOOOOOOOOOo   oooooooooooo    OOOOOo ",
" ++++++++++o                   oooooo ",
" ..........o OOOOOOOOOOOOOOOOO.OOOOO. ",
" ..........o OOOOOOOOOOOOOOOOOXOOOOOo ",
" ..........o OOOOOOOOOOOOOOOOOXOOOOOo ",
" ..........o OOOOOOOOOOOOOOOOOXOOOOOo ",
" OOOOOOOOOOo OOOOOOOOOOOOOOOOOXOOOOOo ",
" OOOOOOOOOOo XXXXXXXXXXXXXXXXXoXXXXXo ",
" ++++++++++o..............XXXXoXXXXXo ",
" ..........................oXXoXXXXXo ",
" ............oooooooooooo..oXXoXXXXXo ",
" ............o@@@@@@@@@@@..oXXoXXXXXo ",
" ............o@#######@@@..oooooooooo ",
" ............o@@@@@@@@@@@..o       $  ",
" ............o@#####@@@@@..o       $  ",
"  ooooooooo..o@@@@@@@@@@@..o        $ ",
"  $        ..o@#########@..o       $  ",
"  $        ..o@@@@@@@@@@@..o      $   ",
"  $        ..o@@@@@@@@@@@..o       $  ",
" $         ................o        $ ",
"  $        ...............         $  ",
"   $        oooooooooooooo        $   ",
"  $            XX%%%%XXo           $  ",
" $       ....................o      $ ",
"  $     .o.o.o.o.o.o.o.o.o.o..o    $  ",
"  $$$$ ........................o$$$$  ",
"       %%%%%%%%%%%%%%%%%%%%%%%%o      ",
"       oooooooooooooooooooooooo       "};
